[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "relaybus-nats"
version = "0.0.8"
description = "Relaybus NATS publisher and subscriber"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["nats-py>=2.7.2"]

[tool.hatch.build.targets.wheel]
packages = ["relaybus_nats", "relaybus_core"]
