[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "relaybus-amqp"
version = "0.0.8"
description = "Relaybus AMQP subscriber"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["pika>=1.3.2"]

[tool.hatch.build.targets.wheel]
packages = ["relaybus_amqp", "relaybus_core"]
